FROM supervisely/supervisely/base-py-sdk:6.72.70

#export-activity-as-csv
#labeling-jobs-stats
#labeling-events-stats
#labeling-queues
#labeler-first-time-through
#invite-users-to-team-from-csv
#exams
#consensus
#create-users-from-csv
#export-items-after-labeling-job-review
#group-reference-objects-into-batches

supervisely==6.72.70
