FROM supervisely/supervisely/base-py-sdk:6.72.70


# render-video-labels-to-mp4
# video-objects-stats-for-every-class
# compare-models-predictions-on-demo-video
# action-recognition-stats
# classes-stats-for-images
# interactive-objects-distribution
# compare-models-predictions-on-demo-video
# tags-co-occurrence-matrix
# consensus
supervisely==6.72.55

# objects-thumbnails-preview-by-class
supervisely==6.72.55
diskcache==5.2.1

# classes-co-occurrence-matrix
supervisely==6.35.0
supervisely[apps]==6.35.0
seaborn==0.11.0


# thumbnails-preview
supervisely==6.72.55
diskcache==5.2.1

# embeddings-app
supervisely==6.70.15
opencv-python==4.6.0.66
transformers
timm
torch
scikit-learn
umap-learn

# labels-spatial-distribution
supervisely==6.72.56
aniso8601==9.0.1
certifi==2021.10.8
charset-normalizer==2.0.10
click==8.0.3
cycler==0.11.0
Flask==2.0.2
fonttools==4.28.5
idna==3.3
imageio==2.13.5
itsdangerous==2.0.1
kiwisolver==1.3.2
networkx==2.6.3
packaging==21.3
pyparsing==3.0.6
python-dateutil==2.8.2
pytz==2021.3
PyWavelets==1.2.0
six==1.16.0
tenacity==8.0.1
tifffile==2021.11.2
websocket-client==1.2.3

# classification-metrics
supervisely==6.69.76
scikit-learn



# instance-segmentation-metrics
supervisely==6.72.2
scikit-learn
pycocotools
Cython

# project-3d-stats
supervisely==6.72.55
open3d==0.15.2