FROM supervisely/supervisely/base-py-sdk:6.72.70


# render-video-labels-to-mp4
# video-objects-stats-for-every-class
# compare-models-predictions-on-demo-video
# action-recognition-stats
# classes-stats-for-images
# interactive-objects-distribution
# compare-models-predictions-on-demo-video
# tags-co-occurrence-matrix
# consensus
supervisely==6.72.55

# objects-thumbnails-preview-by-class
supervisely==6.72.55
diskcache==5.2.1

# classes-co-occurrence-matrix
supervisely==6.35.0
supervisely[apps]==6.35.0
seaborn==0.11.0


# thumbnails-preview
supervisely==6.72.55
diskcache==5.2.1

# embeddings-app
supervisely==6.70.15
opencv-python==4.6.0.66
transformers
timm
torch
scikit-learn
umap-learn

# labels-spatial-distribution
supervisely==6.72.56

# classification-metrics
supervisely==6.69.76
scikit-learn



# instance-segmentation-metrics
supervisely==6.72.2
scikit-learn
pycocotools
Cython

# project-3d-stats
supervisely==6.72.55
open3d==0.15.2