name: Build All Dockerfiles

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Docker Image Tag"
        required: true
        default: ""

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Collaboration build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/collaboration/Dockerfile
          tags: supervisely/collaboration:${{ github.event.inputs.tag_version }}

      - name: Data Operations build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/data-operations/Dockerfile
          tags: supervisely/data-operations:${{ github.event.inputs.tag_version }}

      - name: Development build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/development/Dockerfile
          tags: supervisely/development:${{ github.event.inputs.tag_version }}

      - name: Import - Export build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/import-export/Dockerfile
          tags: supervisely/import-export:${{ github.event.inputs.tag_version }}

      - name: Labeling build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/labeling/Dockerfile
          tags: supervisely/labeling:${{ github.event.inputs.tag_version }}

      - name: Synthetic build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/synthetic/Dockerfile
          tags: supervisely/synthetic:${{ github.event.inputs.tag_version }}

      - name: System build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/system/Dockerfile
          tags: supervisely/system:${{ github.event.inputs.tag_version }}

      - name: Visualization - Stats build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: images/visualization-stats/Dockerfile
          tags: supervisely/visualization-stats:${{ github.event.inputs.tag_version }}
